package com.example.zikirmatik;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.TextView;

import java.util.ArrayList;

public class esmaulhusna extends AppCompatActivity {

    private static final String TAG = "esmaulhusna";


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_esmaulhusna);
        Log.d(TAG,"onCreate: Started.");

        ListView esmaulHusnaList = findViewById(R.id.esmaulHusnaList);

        esmaulhsn esmaulhsn1 = new esmaulhsn("Allah","(66)");
        esmaulhsn esmaulhsn2 = new esmaulhsn("Er-Rahmân","(298)");
        esmaulhsn esmaulhsn3 = new esmaulhsn("Er-Rahîm","(258)");
        esmaulhsn esmaulhsn4 = new esmaulhsn("El-Melik","(90)");
        esmaulhsn esmaulhsn5 = new esmaulhsn("El-Kuddûs","(170)");
        esmaulhsn esmaulhsn6 = new esmaulhsn("Es-Selâm","(131)");
        esmaulhsn esmaulhsn7 = new esmaulhsn("El-Mü’min","(137)");
        esmaulhsn esmaulhsn8 = new esmaulhsn("El-Muheymin","(145)");
        esmaulhsn esmaulhsn9 = new esmaulhsn("El-Aziz","(94)");
        esmaulhsn esmaulhsn10 = new esmaulhsn("El-Cebbâr","(206)");
        esmaulhsn esmaulhsn11 = new esmaulhsn("El-Mütekebbir","(662)");
        esmaulhsn esmaulhsn12 = new esmaulhsn("El-Hâlık","(731)");
        esmaulhsn esmaulhsn13 = new esmaulhsn("El-Bâri","(214)");
        esmaulhsn esmaulhsn14 = new esmaulhsn("El-Musavvir","(336)");
        esmaulhsn esmaulhsn15 = new esmaulhsn("El-Gaffâr","(1.281)");
        esmaulhsn esmaulhsn16 = new esmaulhsn("El-Kahhâr","(306)");
        esmaulhsn esmaulhsn17 = new esmaulhsn("El-Vehhâb","(14)");
        esmaulhsn esmaulhsn18 = new esmaulhsn("Er-Rezzâk","(308)");
        esmaulhsn esmaulhsn19 = new esmaulhsn("El-Fettâh","(489)");
        esmaulhsn esmaulhsn20 = new esmaulhsn("El-Alim","(150)");
        esmaulhsn esmaulhsn21 = new esmaulhsn("El-Kâbid","(903)");
        esmaulhsn esmaulhsn22 = new esmaulhsn("El-Bâsit","(72)");
        esmaulhsn esmaulhsn23 = new esmaulhsn("El-Hafid","(1.481)");
        esmaulhsn esmaulhsn24 = new esmaulhsn("Er-Rafi’","(351)");
        esmaulhsn esmaulhsn25 = new esmaulhsn("El-Muiz","(117)");
        esmaulhsn esmaulhsn26 = new esmaulhsn("El-Muzil","(770)");
        esmaulhsn esmaulhsn27 = new esmaulhsn("Es-Semi’","(180)");
        esmaulhsn esmaulhsn28 = new esmaulhsn("El-Basir","(112)");
        esmaulhsn esmaulhsn29 = new esmaulhsn("El-Hakem","(68)");
        esmaulhsn esmaulhsn30 = new esmaulhsn("El-Adl","(104)");
        esmaulhsn esmaulhsn31 = new esmaulhsn("El-Latîf","(129)");
        esmaulhsn esmaulhsn32 = new esmaulhsn("El-Habîr","(812)");
        esmaulhsn esmaulhsn33 = new esmaulhsn("El-Halîm","(88)");
        esmaulhsn esmaulhsn34 = new esmaulhsn("El-Azîm","(1.020)");
        esmaulhsn esmaulhsn35 = new esmaulhsn("El-Gafûr","(1.286)");
        esmaulhsn esmaulhsn36 = new esmaulhsn("Es-Sekûr","(526)");
        esmaulhsn esmaulhsn37 = new esmaulhsn("El-Aliyy","(110)");
        esmaulhsn esmaulhsn38 = new esmaulhsn("El-Kebîr","(232)");
        esmaulhsn esmaulhsn39 = new esmaulhsn("El-Hafîz","(998)");
        esmaulhsn esmaulhsn40 = new esmaulhsn("El-Mukît","(550)");
        esmaulhsn esmaulhsn41 = new esmaulhsn("El-Hasîb","(80)");
        esmaulhsn esmaulhsn42 = new esmaulhsn("El-Celîl","(5.329)");
        esmaulhsn esmaulhsn43 = new esmaulhsn("El-Kerîm","(270)");
        esmaulhsn esmaulhsn44 = new esmaulhsn("Er-Rakîb","(312)");
        esmaulhsn esmaulhsn45 = new esmaulhsn("El-Mücîb","(3.025)");
        esmaulhsn esmaulhsn46 = new esmaulhsn("El-Vâsi’","(137)");
        esmaulhsn esmaulhsn47 = new esmaulhsn("El-Hakîm","(6.084)");
        esmaulhsn esmaulhsn48 = new esmaulhsn("El-Vedûd","(400)");
        esmaulhsn esmaulhsn49 = new esmaulhsn("El-Mecîd","(3.249)");
        esmaulhsn esmaulhsn50 = new esmaulhsn("El-Bâis","(573)");
        esmaulhsn esmaulhsn51 = new esmaulhsn("Es-Sehîd","(319)");
        esmaulhsn esmaulhsn52 = new esmaulhsn("El-Hak","(108)");
        esmaulhsn esmaulhsn53 = new esmaulhsn("El-Vekîl","(66)");
        esmaulhsn esmaulhsn54 = new esmaulhsn("El-Kavî","(116)");
        esmaulhsn esmaulhsn55 = new esmaulhsn("El-Metîn","(500)");
        esmaulhsn esmaulhsn56 = new esmaulhsn("El-Veliyy","(2.116)");
        esmaulhsn esmaulhsn57 = new esmaulhsn("El-Hamîd","(3.844)");
        esmaulhsn esmaulhsn58 = new esmaulhsn("El-Muhsî","(148)");
        esmaulhsn esmaulhsn59 = new esmaulhsn("El-Mübdi","(57)");
        esmaulhsn esmaulhsn60 = new esmaulhsn("El-Muîd","(124)");
        esmaulhsn esmaulhsn61 = new esmaulhsn("El-Muhyî","(68)");
        esmaulhsn esmaulhsn62 = new esmaulhsn("El-Mumît","(490)");
        esmaulhsn esmaulhsn63 = new esmaulhsn("El-Hay","(18-324)");
        esmaulhsn esmaulhsn64 = new esmaulhsn("El-Kayyûm","(156)");
        esmaulhsn esmaulhsn65 = new esmaulhsn("El-Vâcid","(196)");
        esmaulhsn esmaulhsn66 = new esmaulhsn("El-Mâcid","(48)");
        esmaulhsn esmaulhsn67 = new esmaulhsn("El-Vâhid/El-Ehad","(3.669)");
        esmaulhsn esmaulhsn68 = new esmaulhsn("Es-Samed","(134)");
        esmaulhsn esmaulhsn69 = new esmaulhsn("El-Kâdir","(305)");
        esmaulhsn esmaulhsn70 = new esmaulhsn("El-Muktedir","(744)");
        esmaulhsn esmaulhsn71 = new esmaulhsn("El-Mukaddim","(184)");
        esmaulhsn esmaulhsn72 = new esmaulhsn("El-Muahhir","(847)");
        esmaulhsn esmaulhsn73 = new esmaulhsn("El-Evvel","(37)");
        esmaulhsn esmaulhsn74 = new esmaulhsn("El-Âhir","(801)");
        esmaulhsn esmaulhsn75 = new esmaulhsn("Ez Zâhir","(1.106)");
        esmaulhsn esmaulhsn76 = new esmaulhsn("El-Müteâlî","(551)");
        esmaulhsn esmaulhsn77 = new esmaulhsn("El-Bâtın","(62)");
        esmaulhsn esmaulhsn78 = new esmaulhsn("El-Vâlî","(47)");
        esmaulhsn esmaulhsn79 = new esmaulhsn("El-Berr","(202)");
        esmaulhsn esmaulhsn80 = new esmaulhsn("Et-Tevvâb","(409)");
        esmaulhsn esmaulhsn81 = new esmaulhsn("El-Müntekım","(630)");
        esmaulhsn esmaulhsn82 = new esmaulhsn("El-Afuvv","(156)");
        esmaulhsn esmaulhsn83 = new esmaulhsn("Er-Raûf","(287)");
        esmaulhsn esmaulhsn84 = new esmaulhsn("Mâlikü’l-Mülk","(212)");
        esmaulhsn esmaulhsn85 = new esmaulhsn("Zü’l-Celâli ve’l-Ikrâm","(1.100)");
        esmaulhsn esmaulhsn86 = new esmaulhsn("El-Muksit","(209)");
        esmaulhsn esmaulhsn87 = new esmaulhsn("El-Câmi","(114)");
        esmaulhsn esmaulhsn88 = new esmaulhsn("El-Ganî","(1.060)");
        esmaulhsn esmaulhsn89 = new esmaulhsn("El-Mugnî","(1.100)");
        esmaulhsn esmaulhsn90 = new esmaulhsn("El-Mâni’","(161)");
        esmaulhsn esmaulhsn91 = new esmaulhsn("Ed-Dârr","(1.001)");
        esmaulhsn esmaulhsn92 = new esmaulhsn("En-Nâfi’","(201)");
        esmaulhsn esmaulhsn93 = new esmaulhsn("En-Nûr","(256)");
        esmaulhsn esmaulhsn94 = new esmaulhsn("El-Hâdî","(400)");
        esmaulhsn esmaulhsn95 = new esmaulhsn("El-Bedî’","(86)");
        esmaulhsn esmaulhsn96 = new esmaulhsn("El-Bâkî","(113)");
        esmaulhsn esmaulhsn97 = new esmaulhsn("El-Vâris","(707)");
        esmaulhsn esmaulhsn98 = new esmaulhsn("Er-Resîd","(514)");
        esmaulhsn esmaulhsn99 = new esmaulhsn("Es-Sabûr","(298)");


        ArrayList<esmaulhsn> esmList = new ArrayList<>();
        esmList.add(esmaulhsn1);
        esmList.add(esmaulhsn2);
        esmList.add(esmaulhsn3);
        esmList.add(esmaulhsn4);
        esmList.add(esmaulhsn5);
        esmList.add(esmaulhsn6);
        esmList.add(esmaulhsn7);
        esmList.add(esmaulhsn8);
        esmList.add(esmaulhsn9);
        esmList.add(esmaulhsn10);
        esmList.add(esmaulhsn11);
        esmList.add(esmaulhsn12);
        esmList.add(esmaulhsn13);
        esmList.add(esmaulhsn14);
        esmList.add(esmaulhsn15);
        esmList.add(esmaulhsn16);
        esmList.add(esmaulhsn17);
        esmList.add(esmaulhsn18);
        esmList.add(esmaulhsn19);
        esmList.add(esmaulhsn20);
        esmList.add(esmaulhsn21);
        esmList.add(esmaulhsn22);
        esmList.add(esmaulhsn23);
        esmList.add(esmaulhsn24);
        esmList.add(esmaulhsn25);
        esmList.add(esmaulhsn26);
        esmList.add(esmaulhsn27);
        esmList.add(esmaulhsn28);
        esmList.add(esmaulhsn29);
        esmList.add(esmaulhsn30);
        esmList.add(esmaulhsn31);
        esmList.add(esmaulhsn32);
        esmList.add(esmaulhsn33);
        esmList.add(esmaulhsn34);
        esmList.add(esmaulhsn35);
        esmList.add(esmaulhsn36);
        esmList.add(esmaulhsn37);
        esmList.add(esmaulhsn38);
        esmList.add(esmaulhsn39);
        esmList.add(esmaulhsn40);
        esmList.add(esmaulhsn41);
        esmList.add(esmaulhsn42);
        esmList.add(esmaulhsn43);
        esmList.add(esmaulhsn44);
        esmList.add(esmaulhsn45);
        esmList.add(esmaulhsn46);
        esmList.add(esmaulhsn47);
        esmList.add(esmaulhsn48);
        esmList.add(esmaulhsn49);
        esmList.add(esmaulhsn50);
        esmList.add(esmaulhsn51);
        esmList.add(esmaulhsn52);
        esmList.add(esmaulhsn53);
        esmList.add(esmaulhsn54);
        esmList.add(esmaulhsn55);
        esmList.add(esmaulhsn56);
        esmList.add(esmaulhsn57);
        esmList.add(esmaulhsn58);
        esmList.add(esmaulhsn59);
        esmList.add(esmaulhsn60);
        esmList.add(esmaulhsn61);
        esmList.add(esmaulhsn62);
        esmList.add(esmaulhsn63);
        esmList.add(esmaulhsn64);
        esmList.add(esmaulhsn65);
        esmList.add(esmaulhsn66);
        esmList.add(esmaulhsn67);
        esmList.add(esmaulhsn68);
        esmList.add(esmaulhsn69);
        esmList.add(esmaulhsn70);
        esmList.add(esmaulhsn71);
        esmList.add(esmaulhsn72);
        esmList.add(esmaulhsn73);
        esmList.add(esmaulhsn74);
        esmList.add(esmaulhsn75);
        esmList.add(esmaulhsn76);
        esmList.add(esmaulhsn77);
        esmList.add(esmaulhsn78);
        esmList.add(esmaulhsn79);
        esmList.add(esmaulhsn80);
        esmList.add(esmaulhsn81);
        esmList.add(esmaulhsn82);
        esmList.add(esmaulhsn83);
        esmList.add(esmaulhsn84);
        esmList.add(esmaulhsn85);
        esmList.add(esmaulhsn86);
        esmList.add(esmaulhsn87);
        esmList.add(esmaulhsn88);
        esmList.add(esmaulhsn89);
        esmList.add(esmaulhsn90);
        esmList.add(esmaulhsn91);
        esmList.add(esmaulhsn92);
        esmList.add(esmaulhsn93);
        esmList.add(esmaulhsn94);
        esmList.add(esmaulhsn95);
        esmList.add(esmaulhsn96);
        esmList.add(esmaulhsn97);
        esmList.add(esmaulhsn98);
        esmList.add(esmaulhsn99);

        final ArrayList<String> esmName = new ArrayList<>();

        esmName.add("Allah");
        esmName.add("Er-Rahmân");
        esmName.add("Er-Rahîm");
        esmName.add("El-Melik");
        esmName.add("El-Kuddûs");
        esmName.add("Es-Selâm");
        esmName.add("El-Mü’min");
        esmName.add("El-Muheymin");
        esmName.add("El-Aziz");
        esmName.add("El-Cebbâr");
        esmName.add("El-Mütekebbir");
        esmName.add("El-Hâlık");
        esmName.add("El-Bâri");
        esmName.add("El-Musavvir");
        esmName.add("El-Gaffâr");
        esmName.add("El-Kahhâr");
        esmName.add("El-Vehhâb");
        esmName.add("Er-Rezzâk");
        esmName.add("El-Fettâh");
        esmName.add("El-Alim");
        esmName.add("El-Kâbid");
        esmName.add("El-Bâsit");
        esmName.add("El-Hafid");
        esmName.add("Er-Rafi’");
        esmName.add("El-Muiz");
        esmName.add("El-Muzil");
        esmName.add("Es-Semi’");
        esmName.add("El-Basir");
        esmName.add("El-Hakem");
        esmName.add("El-Adl");
        esmName.add("El-Latîf");
        esmName.add("El-Habîr");
        esmName.add("El-Halîm");
        esmName.add("El-Azîm");
        esmName.add("El-Gafûr");
        esmName.add("Eş-Şekûr");
        esmName.add("El-Aliyy");
        esmName.add("El-Kebîr");
        esmName.add("El-Hafîz");
        esmName.add("El-Mukît");
        esmName.add("El-Hasîb");
        esmName.add("El-Celîl");
        esmName.add("El-Kerîm");
        esmName.add("Er-Rakîb");
        esmName.add("El-Mücîb");
        esmName.add("El-Vâsi’");
        esmName.add("El-Hakîm");
        esmName.add("El-Vedûd");
        esmName.add("El-Mecîd");
        esmName.add("El-Bâis");
        esmName.add("Eş-Şehîd");
        esmName.add("El-Hak");
        esmName.add("El-Vekîl");
        esmName.add("El-Kavî");
        esmName.add("El-Metîn");
        esmName.add("El-Veliyy");
        esmName.add("El-Hamîd");
        esmName.add("El-Muhsî");
        esmName.add("El-Mübdi");
        esmName.add("El-Muîd");
        esmName.add("El-Muhyî");
        esmName.add("El-Mumît");
        esmName.add("El-Hay");
        esmName.add("El-Kayyûm");
        esmName.add("El-Vâcid");
        esmName.add("El-Mâcid");
        esmName.add("El-Vâhid/El-Ehad");
        esmName.add("Es-Samed");
        esmName.add("El-Kâdir");
        esmName.add("El-Muktedir");
        esmName.add("El-Mukaddim");
        esmName.add("El-Muahhir");
        esmName.add("El-Evvel");
        esmName.add("El-Âhir");
        esmName.add("Ez Zâhir");
        esmName.add("El-Müteâlî");
        esmName.add("El-Bâtın");
        esmName.add("El-Vâlî");
        esmName.add("El-Berr");
        esmName.add("Et-Tevvâb");
        esmName.add("El-Müntekım");
        esmName.add("El-Afuvv");
        esmName.add("Er-Raûf");
        esmName.add("Mâlikü’l-Mülk");
        esmName.add("Zü’l-Celâli ve’l-İkrâm");
        esmName.add("El-Muksit");
        esmName.add("El-Câmi");
        esmName.add("El-Ganî");
        esmName.add("El-Muğnî");
        esmName.add("El-Mâni’");
        esmName.add("Ed-Dârr");
        esmName.add("En-Nâfi’");
        esmName.add("En-Nûr");
        esmName.add("El-Hâdî");
        esmName.add("El-Bedî’");
        esmName.add("El-Bâkî");
        esmName.add("El-Vâris");
        esmName.add("Er-Reşîd");
        esmName.add("Es-Sabûr");

        final ArrayList<String> adetler = new ArrayList<>();

        adetler.add("66");
        adetler.add("298");
        adetler.add("258");
        adetler.add("90");
        adetler.add("170");
        adetler.add("131");
        adetler.add("137");
        adetler.add("145");
        adetler.add("94");
        adetler.add("206");
        adetler.add("662");
        adetler.add("731");
        adetler.add("214");
        adetler.add("336");
        adetler.add("1281");
        adetler.add("306");
        adetler.add("14");
        adetler.add("308");
        adetler.add("489");
        adetler.add("150");
        adetler.add("903");
        adetler.add("72");
        adetler.add("1481");
        adetler.add("351");
        adetler.add("117");
        adetler.add("770");
        adetler.add("180");
        adetler.add("112");
        adetler.add("68");
        adetler.add("104");
        adetler.add("129");
        adetler.add("812");
        adetler.add("88");
        adetler.add("1020");
        adetler.add("1286");
        adetler.add("526");
        adetler.add("110");
        adetler.add("232");
        adetler.add("998");
        adetler.add("550");
        adetler.add("80");
        adetler.add("5329");
        adetler.add("270");
        adetler.add("312");
        adetler.add("3025");
        adetler.add("137");
        adetler.add("6084");
        adetler.add("400");
        adetler.add("3249");
        adetler.add("573");
        adetler.add("319");
        adetler.add("108");
        adetler.add("66");
        adetler.add("116");
        adetler.add("500");
        adetler.add("2116");
        adetler.add("3844");
        adetler.add("148");
        adetler.add("57");
        adetler.add("124");
        adetler.add("68");
        adetler.add("490");
        adetler.add("324");
        adetler.add("156");
        adetler.add("196");
        adetler.add("48");
        adetler.add("3669");
        adetler.add("134");
        adetler.add("305");
        adetler.add("744");
        adetler.add("184");
        adetler.add("847");
        adetler.add("37");
        adetler.add("801");
        adetler.add("1106");
        adetler.add("551");
        adetler.add("62");
        adetler.add("47");
        adetler.add("202");
        adetler.add("409");
        adetler.add("630");
        adetler.add("156");
        adetler.add("287");
        adetler.add("212");
        adetler.add("1100");
        adetler.add("209");
        adetler.add("114");
        adetler.add("1060");
        adetler.add("1100");
        adetler.add("161");
        adetler.add("1001");
        adetler.add("201");
        adetler.add("256");
        adetler.add("400");
        adetler.add("86");
        adetler.add("113");
        adetler.add("707");
        adetler.add("514");
        adetler.add("298");

        final ArrayList<String> anlamlar = new ArrayList<>();

        anlamlar.add("Her türlü istek, tüm duaların kabul olması.");
        anlamlar.add("Dünyada ve ahirette Allah’ın sevgisini kazanmak.");
        anlamlar.add("Maddî ve manevî rızka nail olmak.");
        anlamlar.add("Maddî ve manevî güçlü olmak, insanlara sözlerini anlatıp dinletebilmek, emir sahibi olmak.");
        anlamlar.add("Maddî ve manevî her türlü temizlik, kalp temizliği, ruhî hastalıklardan iyileşmek.");
        anlamlar.add("Korkulan her şeyden emin olmak ve esenliğe çıkmak.");
        anlamlar.add("Güvende olma, güvenilir insan olmak, kötü hastalıklara düşmemek.");
        anlamlar.add("İnsanlardan korunmak ve onların düşüncelerine akıl erdirebilmek.");
        anlamlar.add("Düşmanlara galip gelmek.");
        anlamlar.add("İstek ve arzuların olması, insanların ve cinlerin şerrinden emin olmak.");
        anlamlar.add("İzzet, refah ve gerçek büyüklüğe erişmek, halk tarafından sevilmek.");
        anlamlar.add("İşlerde üzüntü ve sıkıntıdan kurtulmak, başarılı olmak.");
        anlamlar.add("İşte başarılı olmak, maddî ve manevî sıkıntılardan kurtulmak.");
        anlamlar.add("Maksat ve meramına ulaşmak ve ifade etmek, en zor işleri başarmak ve bir işte uzmanlaşmak.");
        anlamlar.add("Bağışlanmak ve günahlardan korunmak.");
        anlamlar.add("Zalimlerin ve din düşmanlarının kahrından kurtulmak.");
        anlamlar.add("Sıkıntısız ve maddî açıdan rahat bir hayat sürmek.");
        anlamlar.add("Bol rızıklı bir ömür geçirmek.");
        anlamlar.add("Maddî ve manevî hayır kapılarının açılması, ticarette başarıya ulaşmak.");
        anlamlar.add("İlim zenginliği için.");
        anlamlar.add("Zalimin zulmünden kurtulmak.");
        anlamlar.add("Rızkının genişlemesi ve bereketin artması.");
        anlamlar.add("Kötüden, kötülerden ve belalardan korunmak.");
        anlamlar.add("İnsanlar içinde ve işinde yükselmek, tevazu sahibi olmak.");
        anlamlar.add("Fakir ve zelillikten kurtulmak.");
        anlamlar.add("Düşmanları zelil etmek.");
        anlamlar.add("Duaların kabul olması.");
        anlamlar.add("Acziyetin kalkması, basiretli olmak.");
        anlamlar.add("Haklı davasını kazanmak, insanlar arasında hak ile hüküm vermek.");
        anlamlar.add("Adaletli olmak, haklı davayı kazanmak.");
        anlamlar.add("Dileklerin olması, kısmet ve rızkın artması.");
        anlamlar.add("Hafıza ve idrakin genişlemesi.");
        anlamlar.add("Ahlâk güzelliği ve yumuşak huylu olmak, hiddet ve sinirin gitmesi.");
        anlamlar.add("Sözünün tesirli olması ve sözü dinlenir olmak.");
        anlamlar.add("Günahların affı ve kötü ahlâktan korunmak.");
        anlamlar.add("Talihin açıklığı, kendine verilen nimetlerin şükrünü eda etmek, bol rızık için.");
        anlamlar.add("Zilletten kurtulmak, ilim, derecelerin artması.");
        anlamlar.add("Maddî ve manevî büyüklük, hürmet sahibi olmak.");
        anlamlar.add("Nefsinin ve malının korunması.");
        anlamlar.add("Muhtaç olunan şeyi kazanmak ve rızık.");
        anlamlar.add("Herkese karşı açık alınlı olmak.");
        anlamlar.add("Gerçek yüceliğe erişmek, zalim ve zorbayı zelil etmek.");
        anlamlar.add("Bol rızık sahibi olmak, cömert olmak ve kolaylıklara nail olmak.");
        anlamlar.add("Her işte Allah’ın koruması altında olmak, bunu hissetmek, hafızasının kuvvetlenmesi.");
        anlamlar.add("Duaların kabul olunması.");
        anlamlar.add("Ömür uzunluğu, sıhhat ve rızık genişliği için.");
        anlamlar.add("İlim ve hikmet sahibi olmak, uzağı görmek, hikmetli iş yapmak.");
        anlamlar.add("İnsanların sevgisini kazanmak.");
        anlamlar.add("İzzet ve şerefin artması.");
        anlamlar.add("Kuvvetli irade ve alacaklarını almak.");
        anlamlar.add("Şehid olmak, heybetli olmak, halk arasında sevilmek.");
        anlamlar.add("Sağlam bir imana ve doğru bir ibadet hayatına sahip olmak, başladığı işin sonunun gelmesi.");
        anlamlar.add("Allah’tan her türlü yardım görmek.");
        anlamlar.add("Kansızlık ve vücudun güçlü olması, zor işleri kolaylıkla halletmek.");
        anlamlar.add("Maddî ve manevî dayanıklı, sağlam ve iradeli olmak, hastalıklardan kurtulmak.");
        anlamlar.add("Her işte Allah’ın yardımını istemek.");
        anlamlar.add("Kazancın genişlemesi, Allah’ı çokça hamd etmek için yardım istemek.");
        anlamlar.add("Zekânın kuvvetli olması.");
        anlamlar.add("Her işte muvaffak olmak, ummadığı yerden yardım gelmesi.");
        anlamlar.add("Elden kaçanı geri kazanmak, Allah’ın ahirette yeniden dirilme hakikatini ruhlarımıza duyurması.");
        anlamlar.add("İşlerin başarılı olması, hastalıklardan kurtulmak.");
        anlamlar.add("Harama bakmamak, kötülüklerden vazgeçmek, devamlı ahireti hatırlamak.");
        anlamlar.add("Sözün tesirli olması, sözü dinlenir olmak.");
        anlamlar.add("Bütün işlerde yardımı Allah’tan beklemek, isteklere nail olmak, rızkın devamlı olması.");
        anlamlar.add("Aradığını ve kaybettiğini bulmak.");
        anlamlar.add("Kazancın bolluğu ve şerefli bir hayat sahibi olmak.");
        anlamlar.add("Kalbin uyanıklığı, isteklerin olması.");
        anlamlar.add("Hiç kimseye muhtaç olmamak.");
        anlamlar.add("İstediğini yapmaya güç yetirmek.");
        anlamlar.add("Her işte başarılı olmak.");
        anlamlar.add("Daima yükselmek.");
        anlamlar.add("Kötü ve belalı birinin veya bir işin kendinden uzaklaşması.");
        anlamlar.add("Her hayır işinde birinci olmak.");
        anlamlar.add("Ömrün uzun olması.");
        anlamlar.add("Her meselenin zuhuru, açıklığı, gizli olmaması.");
        anlamlar.add("İstediği makama gelmek ve yüceliğe ermek.");
        anlamlar.add("Nefsi mutmain ve kalbi geniş olmak, iç rahatlığının artması.");
        anlamlar.add("Sözünün tesirli olması, insanların kendini sevmesi.");
        anlamlar.add("Her halukarda iyilik bulmak.");
        anlamlar.add("Tövbelerin kabul olması.");
        anlamlar.add("Zulüm ve fenalıklardan korunmak.");
        anlamlar.add("Rızık bolluğu, kalp huzuru, affedilmek.");
        anlamlar.add("Merhametinin artması, hiçbir varlıktan zarar görmemek.");
        anlamlar.add("Mal ve kazanca zarar gelmemesi, maddî ve manevî derecelerin artması.");
        anlamlar.add("İşlerin kolay ve âsân olması, insanların kendini sevmesi.");
        anlamlar.add("Eşlerin arasını düzeltmek ve adaletli olmak.");
        anlamlar.add("Küsleri barıştırmak ve hayırların birleşip toplanması.");
        anlamlar.add("Gerçek zenginlik, servet ve geniş rızık, insanlar tarafından sevilmek.");
        anlamlar.add("Geçim genişliği, bol rızık ve zenginlik.");
        anlamlar.add("Kaza ve belalardan emin olmak.");
        anlamlar.add("Zararlı kişilerden emin olmak ve onları Allah’a havale etmek.");
        anlamlar.add("Hastalıklardan korunmak, şifa bulmak, zararlardan uzak durmak.");
        anlamlar.add("Doğruyu ve yanlışı görüp kalp nuruna sahip olmak.");
        anlamlar.add("Doğru yolu bulmak ve çocuklarının serkeş olmaması.");
        anlamlar.add("Allah’ın yardımına nail olmak, maddî ve manevî güzellik için.");
        anlamlar.add("Ömrün uzunluğu ve sağlıklı olmak.");
        anlamlar.add("Uzun ömür, bol mal, şeref ve rızık sahibi olmak.");
        anlamlar.add("Güzel ahlâk sahibi olmak, kötü alışkanlıklardan korunmak.");
        anlamlar.add("Başladığı işi kolay bitirmek, sinirini yenmek ve sabırlı olmak.");





        EsmListAdapter adapter = new EsmListAdapter(this,R.layout.adapter_view_layout,esmList);
        esmaulHusnaList.setAdapter(adapter);

        esmaulHusnaList.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Intent intent = new Intent(getApplicationContext(),esmaulHusnaOkunus.class);
                intent.putExtra("title",esmName.get(position));
                intent.putExtra("adetler",adetler.get(position));
                intent.putExtra("tesbih",anlamlar.get(position));
                startActivity(intent);
            }
        });


    }
}